version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
      - primo-explore-eluna-workshop
      - quay.io/nyulibraries/eluna-2019-devday-advanced-workshop
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
      VIEW: NYU
    ports:
    - 8003:8003
    - 3001:3001
    volumes:
    - ./primo-explore/custom:/app/primo-explore/custom/
    - ./primo-explore/modules/primo-explore-custom-search-bar-sub-menu/dist:/app/primo-explore/modules/primo-explore-custom-search-bar-sub-menu/dist

  create-package:
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
      VIEW: NYU
    ports:
    - 8003:8003
    - 3001:3001
    command: yarn create-package
    volumes:
    - ./primo-explore/custom:/app/primo-explore/custom/
    - ./packages:/app/packages/